'use client';

import { FC } from 'react';
import { Column, Grid } from '@carbon/react';
import TaxonomyTree from './graphics/TaxonomyTree';

import styles from './Taxonomy.module.scss';

type Taxonomy = {
  //
};

const StartExperimenting: FC<Taxonomy> = () => (
  <section className={styles.pane}>
    <Grid className={styles.grid}>
      <Column
        className={styles.column}
        lg={{ span: 16 }}
        md={{ span: 8 }}
        sm={{ span: 4 }}
      >
        <TaxonomyTree />
        <div className={styles.content}>
          <h2 className={styles.content__header}>Taxonomy</h2>
          <p className={styles.content__subhead}>
            This solves the problem of being able to generate enough diversity
            in synthetic data, because teacher models are quite uniform without
            them. All contributions and synthetic data generated by the project
            will be available.
          </p>
        </div>
      </Column>
    </Grid>
  </section>
);

export default StartExperimenting;
